import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = {
  "common": {
    "ratelAI": "Ratel AI",
    "cancel": "Cancel",
    "loading": "Loading...",
    "generating": "Generating...",
    "editing": "Editing...",
    "error": "Oops! Something went wrong. Ratel AI is currently unavailable.",
    "thinking1": "Thinking...",
    "thinking2": "Alright, hang on a moment...",
    "thinking3": "Processing your request..."
  },
  "landing": {
    "title": "Ratel AI",
    "subtitle": "AI for the Ratel Family — Learn. Earn. Grow.",
    "startChatting": "Start Chatting",
    "footer": "A Gemini-powered interface."
  },
  "authModal": {
    "signupTitle": "Create your Account",
    "loginTitle": "Welcome Back",
    "forgotPasswordTitle": "Reset Password",
    "signupDescription": "Join to start your journey of discovery.",
    "loginDescription": "Log in to access your conversations.",
    "forgotPasswordDescription": "Enter your email and we'll send you a link to reset your password.",
    "nicknameLabel": "Nickname",
    "nicknamePlaceholder": "e.g., Curious Explorer",
    "emailLabel": "Email Address",
    "emailPlaceholder": "you@example.com",
    "passwordLabel": "Password",
    "passwordPlaceholder": "Enter your password",
    "confirmPasswordLabel": "Confirm Password",
    "signupButton": "Create Account",
    "loginButton": "Log In",
    "forgotPasswordButton": "Send Reset Link",
    "forgotPasswordLink": "Forgot Password?",
    "switchToLogin": "Already have an account?",
    "switchToLoginLink": "Log In",
    "switchToSignup": "Don't have an account?",
    "switchToSignupLink": "Sign Up",
    "backToLogin": "Back to Log In",
    "resetLinkSent": "If an account with that email exists, a reset link has been sent.",
    "rememberMe": "Remember me",
    "error": {
        "default": "An unexpected error occurred.",
        "nicknameRequired": "Please enter a nickname.",
        "emailRequired": "Please enter a valid email address.",
        "passwordRequired": "Password must be at least 6 characters.",
        "passwordsDoNotMatch": "Passwords do not match.",
        "userExists": "An account with this email already exists.",
        "invalidCredentials": "Invalid email or password."
    }
  },
  "sidebar": {
    "newChat": "New Chat",
    "imageStudio": "Image",
    "audioStudio": "Audio",
    "videoStudio": "Video",
    "hustleStudio": "Hustle",
    "learnStudio": "Learn",
    "communityStudio": "Community",
    "marketFinder": "Market",
    "clearChat": "Clear Chat",
    "history": "History",
    "noHistory": "No history yet.",
    "settings": "Settings",
    "contactUs": "Contact Us",
    "supportUs": "Support Us",
    "logout": "Log out",
    "openMenu": "Open Menu",
    "search": "Search history...",
    "rename": "Rename",
    "delete": "Delete",
    "upgradeToPro": "Upgrade to Pro",
    "level": "Level {{level}}",
    "xp": "XP"
  },
  "tones": {
      "normal": "Normal",
      "funny": "Funny",
      "pidgin": "Pidgin"
  },
  "chatWindow": {
    "placeholderTitle": "How can I help you today?",
    "placeholderSubtitle": "Select a mode from the sidebar or just start typing to chat.",
    "suggestion1": "Give me business ideas for ₦10,000",
    "suggestion2": "Teach me about video editing",
    "suggestion3": "Wetin dey sup?",
    "suggestion4": "Explain how photosynthesis works"
  },
  "chatInput": {
    "placeholder": "Ask Ratel AI anything...",
    "listening": "Listening...",
    "noSpeechError": "I didn't catch that. Please try again.",
    "attachImage": "Attach image",
    "stopRecording": "Stop recording",
    "startRecording": "Start recording",
    "sendMessage": "Send message",
    "removeImage": "Remove image"
  },
  "chatMessage": {
    "userUploadAlt": "User upload",
    "generatedImageAlt": "Generated by Ratel AI",
    "generatedVideoAlt": "Generated by Ratel AI",
    "expandedImageAlt": "Expanded view",
    "copy": "Copy message",
    "stopSpeaking": "Stop speaking",
    "readAloud": "Read aloud",
    "delete": "Delete message",
    "editPrompt": "Edit prompt",
    "expandImage": "Expand image",
    "downloadImage": "Download image",
    "downloadVideo": "Download video",
    "showMore": "Show more",
    "showLess": "Show less",
    "sources": "Sources"
  },
  "hustleStudio": {
    "title": "Hustle Mode",
    "description": "Enter your budget or a skill you have to get realistic business ideas tailored for Nigeria.",
    "placeholder": "e.g., ₦10,000 or 'Graphic Design'",
    "button": "Get Ideas"
  },
  "learnStudio": {
      "title": "Learn Mode",
      "description": "Choose a digital skill to start your daily lesson.",
      "skills": {
          "video": "Video Editing",
          "coding": "Coding Basics",
          "canva": "Canva Design",
          "ai": "Using AI"
      }
  },
  "community": {
    "feedTitle": "Feed",
    "leaderboardTitle": "Leaderboard",
    "rewardsTitle": "Rewards",
    "telegramTitle": "My Telegram",
    "postPlaceholder": "What's on your mind, {{name}}?",
    "postButton": "Post",
    "uploadImage": "Upload Image",
    "commentPlaceholder": "Write a comment...",
    "like": "Like",
    "comment": "Comment",
    "comments": "Comments",
    "likedByYou": "You liked this",
    "weeklyRanking": "Weekly Ranking",
    "points": "Points",
    "yourPoints": "Your Points Balance",
    "rewardsDescription": "Convert your points into cool rewards! Keep engaging to earn more.",
    "claimReward": "Claim",
    "rewardData": "{{amount}} Data",
    "rewardAirtime": "₦{{amount}} Airtime",
    "telegramDescription": "Connect your Telegram account to share posts and see messages from the Ratel Community group right here in the feed.",
    "telegramUsernameLabel": "Your Telegram Username",
    "telegramUsernamePlaceholder": "e.g., your_username",
    "connectButton": "Connect",
    "connectedStatus": "Connected as @{{username}}",
    "disconnectButton": "Disconnect",
    "fromTelegram": "from Telegram"
  },
   "marketStudio": {
    "title": "AI Market Finder",
    "description": "Tell me what you want to buy or sell, and where you are. I'll search the web to find local markets and vendors for you.",
    "itemLabel": "What do you want to find?",
    "itemPlaceholder": "e.g., Cheap Android phones, second-hand laptops",
    "locationLabel": "Where are you located?",
    "locationPlaceholder": "e.g., Computer Village, Ikeja, Lagos",
    "button": "Find Markets"
  },
  "profileStudio": {
      "title": "My Profile",
      "joined": "Joined",
      "topInterest": "Top Interest",
      "noInterests": "Not yet determined"
  },
  "imageStudio": {
    "title": "Image Studio",
    "generateTab": "Generate",
    "editTab": "Edit",
    "promptLabel": "Describe the image you want to create:",
    "promptPlaceholder": "e.g., A majestic lion with a crown of stars",
    "aspectRatioLabel": "Aspect Ratio:",
    "square": "Square",
    "landscape": "Landscape",
    "portrait": "Portrait",
    "generateButton": "Generate Image",
    "uploadLabel": "Upload an image to edit:",
    "removeImage": "Remove image",
    "uploadPlaceholderClick": "Click to upload",
    "uploadPlaceholderDrag": "or drag and drop",
    "uploadPlaceholderFormats": "PNG, JPG, WEBP",
    "editPromptLabel": "Describe the changes you want to make:",
    "editPromptPlaceholder": "e.g., Add a birthday hat to the subject",
    "applyEditsButton": "Apply Edits"
  },
  "audioStudio": {
    "title": "Audio Studio",
    "generatingFeedback": "The Oracle is preparing your audio...",
    "generationFailed": "Audio generation failed: {{error}}",
    "unknownError": "An unknown error occurred.",
    "playbackFailed": "Playback failed: {{error}}",
    "previewFailed": "Could not generate voice preview.",
    "textLabel": "Text to generate:",
    "textPlaceholder": "Enter the text you want the Oracle to speak...",
    "voiceLabel": "Voice:",
    "previewVoice": "Preview voice {{voiceName}}",
    "previewText": "Hello, I can read any text you provide.",
    "generateButton": "Generate Audio",
    "generatedAudio": "Generated Audio",
    "stop": "Stop",
    "play": "Play",
    "download": "Download Audio",
    "delete": "Delete Audio"
  },
  "videoStudio": {
    "title": "Video Studio",
    "promptLabel": "Describe the video you want to create:",
    "promptPlaceholder": "e.g., A cinematic shot of a futuristic city at sunset",
    "info": "Video generation can take several minutes. Please be patient while Ratel AI works its magic.",
    "generateButton": "Generate Video",
    "uploadLabel": "Upload an image (optional):",
    "removeImage": "Remove image",
    "aspectRatioLabel": "Aspect Ratio:",
    "square": "Square (1:1)",
    "landscape": "Landscape (16:9)",
    "portrait": "Portrait (9:16)",
    "qualityLabel": "Video Quality:",
    "qualityStandard": "Standard",
    "qualityHigh": "High",
    "imageToVideoDisclaimer": "Heads up: The AI uses your image as inspiration. Exact details, especially faces, may be altered during the video generation process."
  },
  "settings": {
    "title": "Settings",
    "appearance": {
      "title": "Appearance",
      "galleryLabel": "Choose a background from the gallery:",
      "uploadButton": "Upload Image",
      "removeButton": "Remove Background"
    },
    "customInstructions": {
      "title": "Custom Instructions",
      "nicknameLabel": "Nickname",
      "nicknamePlaceholder": "How Ratel AI will call you",
      "aboutYouLabel": "About You",
      "aboutYouPlaceholder": "What would you like Ratel AI to know about you to provide better responses?",
      "expectationsLabel": "Expectations",
      "expectationsPlaceholder": "How would you like Ratel AI to respond?"
    },
    "memory": {
      "title": "Memory",
      "savedMemories": "Reference saved memories",
      "chatHistory": "Reference chat history"
    },
    "responses": {
      "title": "Responses",
      "voicePreference": "Voice Preference"
    },
    "notifications": {
      "title": "Notifications & Security",
      "pushLabel": "Push Notifications",
      "pushDescription": "Get notified when Ratel responds to requests that take time, like research or image generation.",
      "mfaLabel": "Multi-factor authentication",
      "mfaDescription": "Require an extra security challenge when logging in."
    },
    "language": {
        "title": "Language",
        "label": "Choose your preferred language",
        "en": "English",
        "fr": "Français (French)",
        "am": "አማርኛ (Amharic)",
        "ng": "Nigerian Pidgin",
        "sw": "Kiswahili (Swahili)"
    },
    "logout": "Log out of this device"
  },
  "contact": {
    "title": "Contact Us",
    "getInTouch": "Get in Touch",
    "intro": "Have questions, feedback, or need support? We'd love to hear from you. Please reach out to our team, and we'll get back to you as soon as possible.",
    "supportEmail": "Support Email:",
    "formTitle": "Send us a message",
    "submitSuccess": "Thank you for your message! We'll get back to you soon.",
    "submitError": "Failed to send message. Please try again later or contact us directly via email.",
    "nameLabel": "Your Name",
    "namePlaceholder": "John Doe",
    "emailLabel": "Your Email",
    "emailPlaceholder": "john.doe@example.com",
    "messageLabel": "Message",
    "messagePlaceholder": "How can we help you?",
    "sendMessage": "Send Message",
    "sending": "Sending..."
  },
  "tasks": {
    "noTasks": "You have no tasks."
  },
  "dialogs": {
    "newChatTitle": "Start a new chat?",
    "newChatMessage": "Your current conversation will be saved. Are you sure you want to start a new chat?",
    "newChatConfirm": "Start New Chat",
    "deleteChatTitle": "Delete this chat?",
    "deleteChatMessage": "This conversation will be permanently deleted. This action cannot be undone.",
    "deleteChatConfirm": "Delete"
  },
  "imageGen": {
      "generating": "Generating your image...",
      "error": "Sorry, I couldn't generate that image. The Oracle might be busy, or the request may have been denied. Please try a different description."
  },
  "imageEdit": {
      "editing": "Editing your image...",
      "error": "Sorry, I couldn't edit that image. Please try again with a different image or prompt."
  },
  "videoGen": {
      "generatingInitial": "Generating your video... this may take a few minutes.",
      "generatingStatus": "Generating video... Status: {{status}}",
      "error": "Sorry, I couldn't generate that video. The Oracle might be busy, or the request may have been denied. Please try a different description."
  },
  "voiceGroups": {
    "premium": "Ratel AI (Premium)",
    "standard": "Browser (Standard)"
  },
  "supportModal": {
    "title": "Support Ratel AI",
    "description": "Your support helps us keep the servers running and continue improving. A single $5 donation makes a big difference. Thank you!",
    "payWithAmount": "Pay $5 with {{method}}",
    "thankYou": "Thank you so much for your support! ❤️",
    "back": "Back",
    "paystackSuccess": "Payment complete! Reference: {{reference}}",
    "paystackClosed": "Payment window closed.",
    "telebirrPendingTitle": "Backend Required",
    "telebirrPendingBody": "A secure backend is required to process Telebirr payments safely. Your app's secret keys must never be exposed in the browser.",
    "telebirrCodeExplanation": "The frontend would make a request to your backend server:",
    "telebirrBackendExplanation": "Your server would then use its secret key to securely communicate with Telebirr and complete the transaction."
  },
  "proModal": {
    "comingSoonTitle": "Ratel AI Pro is Coming Soon!",
    "comingSoonDescription": "We're working hard on exciting new features, including an ad-free experience, unlimited usage, and access to premium AI voices.",
    "gotIt": "Got it!"
  },
  "adBanner": {
    "dismiss": "Dismiss ad"
  },
  "meta": {
    "defaultTitle": "Ratel AI - The Tenacious AI",
    "defaultDescription": "Ratel AI is a tenacious and highly intelligent AI, enhanced with the expertise of a seasoned screenwriter to help with all your creative and analytical needs.",
    "settingsTitle": "Settings - Ratel AI",
    "settingsDescription": "Customize your Ratel AI experience. Adjust custom instructions, appearance, voice preferences, and more.",
    "contactTitle": "Contact Us - Ratel AI",
    "contactDescription": "Get in touch with the Ratel AI team for support, feedback, or inquiries.",
    "chatTitle": "Chat - Ratel AI",
    "newChatTitle": "New Chat - Ratel AI",
    "chatDescription": "Start a new conversation with Ratel AI, your tenacious creative partner.",
    "chatWithTitle": "{{title}} - Ratel AI",
    "chatWithDescription": "An ongoing conversation with Ratel AI about \"{{title}}\"."
  }
};

const fr = { ...en }; // Placeholder for French
const am = { ...en }; // Placeholder for Amharic
const sw = { ...en }; // Placeholder for Swahili
const ng = { ...en, 
    "sidebar": { ...en.sidebar, "newChat": "New Chat", "communityStudio": "Community", "hustleStudio": "Hustle", "learnStudio": "Learn" },
    "community": { ...en.community, "postPlaceholder": "Wetin dey your mind, {{name}}?", "postButton": "Post Am", "like": "Like", "comment": "Comment" }
}; // Placeholder for Pidgin with some examples

i18n
  .use(initReactI18next)
  .init({
    resources: {
      en: { translation: en },
      fr: { translation: fr },
      am: { translation: am },
      ng: { translation: ng },
      sw: { translation: sw },
    },
    lng: localStorage.getItem('ratel_language') || 'en', // Get language from storage or default to 'en'
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false, 
    },
  });

export default i18n;
